autox chart
iter8-tools/hub pull request #12
Opened 2022-05-16 18:15 UTC by sriumcp

Signed-off-by: Srinivasan Parthasarathy <spartha@us.ibm.com>

2022-05-31 13:55 UTC, kalantar commented on charts/autox/README.md
> +**Is your feature request related to a problem? Please describe.**
This is the issue text; is that what we want here?

2022-05-31 18:08 UTC, Alan-Cha commented on charts/autox/README.md
> +Following is an **example** of how the above  solution can be used. Set up autox to kick start a `load-test-http` experiment whenever there are changes deployments with an iter8-specific group annota
```suggestion
The following is an **example** of how the above solution can be used. Set up autox to kick start a `load-test-http` experiment whenever there are changes deployments with an iter8-specific group annotation.
```

2022-06-01 13:00 UTC, sriumcp commented on charts/autox/README.md
> +**Is your feature request related to a problem? Please describe.**
Fixed.

2022-06-01 13:00 UTC, sriumcp commented on charts/autox/README.md
> +Following is an **example** of how the above  solution can be used. Set up autox to kick start a `load-test-http` experiment whenever there are changes deployments with an iter8-specific group annota
Fixed.

2022-06-01 13:00 UTC, sriumcp commented on charts/autox/README.md
> +Should automatically trigger an `http-load-test` for the `new-sevice`.
Fixed.

2022-06-02 19:04 UTC, kalantar approved these changes
lgtm

2022-06-02 19:22 UTC, kalantar requested changes

2022-06-02 19:22 UTC, kalantar commented on charts/autox/templates/deployment.yaml
> +      serviceAccountName: {{ .Release.Name }}
`serviceAccountName` should be a child of the container

2022-06-02 20:17 UTC, sriumcp commented on charts/autox/templates/deployment.yaml
> +      serviceAccountName: {{ .Release.Name }}
I don't think so. `serviceAccountName` belongs to the pod template spec as described above. Perhaps [this accepted answer helps](https://stackoverflow.com/questions/44505461/how-to-configure-a-non-default-serviceaccount-on-a-deployment)?

2022-06-02 20:30 UTC, kalantar commented on charts/autox/templates/deployment.yaml
> +      serviceAccountName: {{ .Release.Name }}
You are right. My mistake. Misread the reference doc.

2022-06-02 20:30 UTC, kalantar approved these changes
lgtm

2022-06-02 20:39 UTC, merged