abn service chart
iter8-tools/hub pull request #13
Opened 2022-05-24 18:02 UTC by kalantar

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

related to https://github.com/iter8-tools/iter8/issues/1263

2022-06-01 16:54 UTC, sriumcp requested changes

2022-06-01 16:54 UTC, sriumcp commented on charts/abn-service/templates/roles.yaml
> +  verbs: ["get", "list"]
The verbs should be `["watch"]` instead of `["get", "list"]`.

2022-06-02 19:27 UTC, kalantar commented on charts/abn-service/templates/deployment.yaml
> +  template:
added

2022-06-02 19:27 UTC, kalantar commented on charts/abn-service/templates/roles.yaml
> +  verbs: ["get", "list"]
fixed

2022-06-06 19:29 UTC, kalantar commented on charts/abn-service/Chart.yaml
> +version: 0.10.1
done

2022-06-07 12:41 UTC, sriumcp commented on charts/abn-service/values.yaml
> +### serviceaccount for execution of service
I think it is better if we start by creating a service account -- and name the account consistently as `{{ .Release.Name }}`.
***
This has two main advantages. The code will get simplified (no `if` branches re: service accounts; always present with a deterministic name), and also RBAC permissions are better isolated -- default service account may be used by other jobs/apps with other permissions, but the a/b/n service account will have clear RBAC permissions meant for it alone.

2022-06-07 12:41 UTC, sriumcp approved these changes
lgtm

2022-07-29 04:20 UTC, sriumcp requested changes
Please see comments on service accounts.

2022-07-29 04:20 UTC, sriumcp commented on charts/abn-service/templates/serviceaccount.yaml
> +{{- if .Values.serviceaccount }}
Could we please use the following definition instead?
```yaml
apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: {{ .Release.Name }}
```

This takes out `.serviceaccount` from `.Values` and also removes all the `if` clauses around the service account. There is a deterministic service account always created and used by this service (something similar is at work for autox).

2022-07-29 04:20 UTC, sriumcp commented on charts/abn-service/values.yaml
> +### serviceaccount for execution of service
Please see the serviceaccount.yaml comment also.

2022-07-29 16:29 UTC, kalantar commented on charts/abn-service/templates/serviceaccount.yaml
> +{{- if .Values.serviceaccount }}
done

2022-07-29 16:30 UTC, kalantar commented on charts/abn-service/values.yaml
> +### serviceaccount for execution of service
done

2022-07-29 17:10 UTC, sriumcp requested changes
Please see comments on annotations/labels.

2022-07-29 17:10 UTC, sriumcp commented on charts/abn-service/templates/deployment.yaml
> +  annotations:
`iter8.tools/revision` is what we currently use for *experiment* revisions. Could we please ditch this annotation? Also, could we please adopt the chart best practices suggested by Helm? 

https://helm.sh/docs/chart_best_practices/labels/

2022-07-29 17:10 UTC, sriumcp commented on charts/abn-service/templates/deployment.yaml
> +  annotations:
Same comment holds for all resource labels/annotations.

2022-07-29 17:45 UTC, kalantar commented on charts/abn-service/templates/deployment.yaml
> +  annotations:
done

2022-07-29 19:37 UTC, sriumcp requested changes
A small (minor) change requested.

2022-07-29 19:37 UTC, sriumcp commented on charts/abn-service/templates/configmap.yaml
> +    app.kubernetes.io/name: {{ .Release.Name }}
Perhaps make this `Iter8 ABn service`? Instead of `{{ .Release.Name }}`. Other annotations/labels look great.

2022-08-02 19:28 UTC, kalantar commented on charts/abn-service/templates/configmap.yaml
> +    app.kubernetes.io/name: {{ .Release.Name }}
modified using recommended approach for helm

2022-08-02 20:22 UTC, sriumcp requested changes

2022-08-02 20:22 UTC, sriumcp commented on charts/abn-service/templates/configmap.yaml
> +  labels:
Don't you want something like 
```yaml
    metadata:
 {{ include "iter8-abn.labels" . | indent 6 }}
```

instead of explicit labels?

2022-08-02 20:22 UTC, sriumcp commented on charts/abn-service/templates/deployment.yaml
> +{{ include "iter8-abn.labels" . | indent 6 }}
I'm not sure if you want this. I think it is preferable to include only those labels in the template metadata that you've included in the selector-match labels clause (so that the deployment selector labels exactly match the pod labels).

2022-08-02 20:22 UTC, sriumcp commented on charts/abn-service/templates/deployment.yaml
> +{{ include "iter8-abn.labels" . | indent 6 }}
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

```
Note:
You must specify an appropriate selector and Pod template labels in a Deployment (in this case, app: nginx).

Do not overlap labels or selectors with other controllers (including other Deployments and StatefulSets). Kubernetes doesn't stop you from overlapping, and if multiple controllers have overlapping selectors those controllers might conflict and behave unexpectedly.
```

Given the aforementioned note by Kubernetes, I think it is a good idea to keep the selector and pod labels to a minimum, e.g., a single app label.

Note that selector labels are distinct from the labels found in the deployment's metadata (there is no connection between them).

2022-08-03 13:01 UTC, kalantar commented on charts/abn-service/templates/configmap.yaml
> +  labels:
yes. oversight. good catch.

2022-08-03 13:09 UTC, kalantar commented on charts/abn-service/templates/deployment.yaml
> +{{ include "iter8-abn.labels" . | indent 6 }}
done

2022-08-03 13:23 UTC, sriumcp requested changes
Namespace requested.

2022-08-03 13:23 UTC, sriumcp commented on charts/abn-service/templates/roles.yaml
> +kind: Role
Metrics role and role bindings are missing the namespace field in metadata. Please add. (BTW, Helm will complain if you try to install this chart with multiple namespaces as it stands right now).

2022-08-03 13:51 UTC, kalantar commented on charts/abn-service/templates/roles.yaml
> +kind: Role
The namespace will be deployment namespace (which is the intended namespace). This similar to every other resource (deployment, configmap, service etc). None of these have a namespace defined either.
The loop over namespaces ends on line 37, before the role/rolebinding without explicit namespaces. Within the loop over namespaces, the role/rolebindings have explicit namespaces defined.

2022-08-03 14:20 UTC, sriumcp approved these changes
lgtm

2022-08-03 17:02 UTC, merged