Add notify templates
iter8-tools/hub pull request #23
Opened 2022-08-23 16:50 UTC by Alan-Cha

Fix #1320

2022-08-23 17:26 UTC, sriumcp requested changes

2022-08-23 17:26 UTC, sriumcp commented on charts/notify/_payload-github.tpl
> +{
Almost there. Could we please remove this from the charts? i.e., create a folder called `templates` directly under the root folder of `hub` repo, and put the templates in there? The README is not required, since this is not really a chart.

2022-08-24 17:28 UTC, sriumcp requested changes

2022-08-24 17:28 UTC, sriumcp commented on charts/iter8lib/templates/_task-github.tpl
> +    payloadTemplateURL: {{ default "https://raw.githubusercontent.com/iter8-tools/hub/blob/main/charts/notify/_payload-github.tpl" .payloadTemplateURL }}
Shouldn't the default URL be `https://raw.githubusercontent.com/iter8-tools/hub/blob/main/templates/_payload-github.tpl`, and similarly for slack?

2022-08-24 17:32 UTC, Alan-Cha commented on charts/iter8lib/templates/_task-github.tpl
> +    payloadTemplateURL: {{ default "https://raw.githubusercontent.com/iter8-tools/hub/blob/main/charts/notify/_payload-github.tpl" .payloadTemplateURL }}
Right, sorry I was a little too hasty

2022-08-24 18:36 UTC, sriumcp approved these changes
lgtm

2022-08-25 16:23 UTC, closed without merging