update iter8lib chart
iter8-tools/hub pull request #31
Opened 2022-09-29 17:47 UTC by kalantar

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

2022-10-03 22:42 UTC, Alan-Cha commented on charts/iter8lib/templates/_experiment.tpl
> +  {{- fail "task name must be one of assess, custommetrics, abnmetrics, grpc, http, ready, github, or slack" -}}
It would be nice if we matched the template order. Should we try to alphabetize them or something?

```suggestion
  {{- fail "task name must be one of assess, abnmetrics, custommetrics, grpc, http, ready, slack, or github" -}}
```

2022-10-03 22:42 UTC, Alan-Cha approved these changes

2022-10-03 23:48 UTC, sriumcp requested changes

2022-10-03 23:48 UTC, sriumcp commented on charts/iter8lib/templates/_k-rolebinding.tpl
> +metadata:
This rolebinding should be removed

2022-10-03 23:48 UTC, sriumcp commented on charts/iter8lib/templates/_k-role.tpl
> +metadata:
This role should be removed

2022-10-04 14:47 UTC, Alan-Cha submitted a review, later dismissed

2022-10-18 14:47 UTC, kalantar commented on charts/iter8lib/templates/_k-role.tpl
> +metadata:
done

2022-10-18 14:48 UTC, kalantar commented on charts/iter8lib/templates/_k-rolebinding.tpl
> +metadata:
done

2022-10-18 14:50 UTC, Alan-Cha approved these changes

2022-10-18 17:45 UTC, sriumcp requested changes
Please see requested changes.

2022-10-18 17:45 UTC, sriumcp commented on charts/iter8/Chart.yaml
> +version: 0.11.3
Let us please move to `0.12.0` of Iter8.

2022-10-18 17:45 UTC, sriumcp commented on charts/iter8lib/Chart.yaml
> +version: 0.11.4
Since we are removing the dependency on `iter8lib`, there is no need to change anything within `iter8lib`. This chart can be left alone.

2022-10-18 17:45 UTC, sriumcp commented on charts/iter8/Chart.yaml
>  description: Iter8 experiment library chart
Let us use "Iter8 experiment chart" as in https://github.com/iter8-tools/iter8/blob/master/charts/iter8/Chart.yaml

2022-10-18 17:45 UTC, sriumcp commented on charts/iter8/Chart.yaml
> +  version: 0.11.4
Let us please get rid of the dependency on `iter8lib`. i.e., the templates and default values (if any) in `iter8lib` will be absorbed into this new `iter8` chart.

2022-10-18 17:45 UTC, sriumcp commented on charts/iter8/Chart.yaml
> +  version: 0.11.4
As a consequence of removing the `iter8lib` dependency, `templates/k8s.yaml` will be the same as 

[https://github.com/iter8-tools/iter8/blob/master/charts/iter8/templates/k8s.yaml](https://github.com/iter8-tools/iter8/blob/master/charts/iter8/templates/k8s.yaml)

2022-10-18 17:45 UTC, sriumcp commented on charts/iter8/Chart.yaml
> +  version: 0.11.4
All the other template changes look good. They will be absorbed into `iter8` chart.

2022-10-18 19:13 UTC, kalantar commented on charts/iter8/Chart.yaml
> +  version: 0.11.4
made all changes

2022-10-18 22:05 UTC, sriumcp approved these changes
lgtm

2022-10-18 22:06 UTC, merged