better promotion support
iter8-tools/hub pull request #42
Opened 2022-12-08 15:11 UTC by kalantar

Changes to templates to better support promotion
- build in assumptions about resource names
- modify configuration configmap

With additional information can now pre-create metrics secrets and narrow rbac

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

2022-12-08 15:13 UTC, kalantar commented
Here is a sample `helm template` command for demonstration. Watch three applications.

```shell
helm template ./abn-service  \
--set "applications.default.frontend.resources={ksvc}" \
--set "applications.default.backend.resources={deployment,service}" \
--set applications.default.backend.maxNumCandidates=2 \
--set "applications.test.iter8.resources={deployment}"
```

2022-12-14 14:55 UTC, sriumcp requested changes

2022-12-14 14:55 UTC, sriumcp commented on charts/abn-service/templates/roles.yaml
> +    verbs: ["watch", "list", "get", "update", "patch"]
Do you need both `update` and `patch`? Perhaps only one of these will suffice?

2022-12-14 14:55 UTC, sriumcp commented on charts/abn-service/templates/roles.yaml
> +  {{- else if eq $r "chaosengine" }}
Please remove chaosengine. Not relevant for AB testing.

2022-12-14 14:55 UTC, sriumcp commented on charts/abn-service/templates/roles.yaml
> +  verbs: ["list", "get", "update", "patch"]
Do you need both update and patch?

2022-12-19 14:18 UTC, kalantar commented on charts/abn-service/templates/roles.yaml
> +    verbs: ["watch", "list", "get", "update", "patch"]
I do not know. I copied what we had for the metric secret earlier. However, will wait with PR and try out to minimize change.

2023-01-12 16:33 UTC, kalantar commented on charts/abn-service/templates/roles.yaml
> +  verbs: ["list", "get", "update", "patch"]
good catch. fixed. also removed `list` since no longer needed

2023-01-16 19:26 UTC, kalantar commented on charts/abn-service/templates/roles.yaml
> +  {{- else if eq $r "chaosengine" }}
removed

2023-01-16 19:27 UTC, kalantar commented on charts/abn-service/templates/roles.yaml
> +    verbs: ["watch", "list", "get", "update", "patch"]
"list" and "watch" seem to be sufficient.

2023-01-17 16:39 UTC, sriumcp approved these changes
lgtm

2023-01-19 20:14 UTC, sriumcp requested changes

2023-01-19 20:14 UTC, sriumcp commented on charts/autox/Chart.yaml
> +appVersion: v0.13
Could you please bump up this chart version also (any change to a chart means bumping up its version, in this case, bumping up the patch version is ok too).

2023-01-19 20:14 UTC, sriumcp commented on charts/iter8/templates/_task-github.tpl
> +    payloadTemplateURL: {{ default "https://raw.githubusercontent.com/iter8-tools/hub/iter8-0.13.0/templates/_payload-github.tpl" .payloadTemplateURL }}
This path doesn't exist... so the change should not be made. Eventually, we can work on a solution that doesn't require version numbers in paths.

2023-01-19 20:14 UTC, sriumcp commented on charts/iter8/templates/_task-slack.tpl
> +    payloadTemplateURL: {{ default "https://raw.githubusercontent.com/iter8-tools/hub/iter8-0.13.0/templates/_payload-slack.tpl" .payloadTemplateURL }}
This path doesn't exist. So change should not be made.

2023-01-19 20:23 UTC, sriumcp approved these changes
lgtm

2023-01-19 20:23 UTC, merged