Multiple endpoints
iter8-tools/hub pull request #54
Opened 2023-02-18 02:38 UTC by Alan-Cha

2023-02-20 17:53 UTC, kalantar requested changes

2023-02-20 17:53 UTC, kalantar commented on charts/iter8/templates/_task-grpc.tpl
> +{{- range $endpointID, $endpoint := $vals.endpoints }}
I think we need a check that `endpoint` contains `host` and `call` (or that it is in `$_`). The earlier check only tested that `endpoints` existed but not the `host` and `call` are defined for each.

2023-02-20 18:05 UTC, sriumcp commented on charts/iter8/templates/_task-grpc.tpl
> +{{- range $endpointID, $endpoint := $vals.endpoints }}
We can keep what the check that's currently in the PR. In addition, we could introduce an additional check for each endpoint (i.e., either this endpoint explicitly specifies host/call, or it is part of the common parameter).

2023-03-03 19:15 UTC, Alan-Cha commented on charts/iter8/templates/_task-grpc.tpl
> +{{- $_ := set $vals "binary-file" "data.bin" }}
New pattern?

2023-03-07 19:46 UTC, kalantar requested changes
The warmup PR (already merged) also changed these files. Is there any impact? Also, the version (in `Chart.yaml` should be updated.

2023-03-08 17:43 UTC, sriumcp requested changes
Update chart version

2023-03-08 17:47 UTC, sriumcp approved these changes
lgtm

2023-03-08 18:49 UTC, kalantar approved these changes

2023-03-08 18:50 UTC, merged